### ISSUE TITLE
Implement Authentication Interceptor

### ISSUE THREAD

**Issue by louislewis2** [louislewis2/Aurelia-Demo#2]
The authentication interceptor needs to be able to perform the following functions.
We are only implementing the responseError(error) method.

It should only be involved for assisting the event when 
the server responds with unauthorised (401).

When it sees the above case, it should perform the following steps.
1. Use the authentication provider and call the refreshToken() method.
2. The above method returns a promise of type LoginResult which has a success property.
3. If the success property is true, the http call that was initially made should be retried.
4. If the success property is false, the system should navigate to the login page.

Below is how the same functionality was achieved using another framework and worked great.
Hopefully it can be used as reference for the implementation.

```
responseError = function (rejection)
    {
        var deferred = $q.defer();
        if (rejection.status === 401)
        {
            this.authService.refreshToken().then(function (response)
            {
                retryHttpRequest(rejection.config, deferred);
            }, function ()
            {
                this.authService.logOut();
                $location.path('/login');
                deferred.reject(rejection);
            });
        } else
        {
            deferred.reject(rejection);
        }
        return deferred.promise;
    }

var retryHttpRequest = function (config, deferred)
    {
        $http = $http || $injector.get('$http');
        $http(config).then(function (response)
        {
            deferred.resolve(response);
        }, function (response)
        {
            deferred.reject(response);
        });
    }

```

**Comment by cmichaelgraham** [comment]
@louislewis2 - very cool - i'll take a look tonight

**Comment by louislewis2** [comment]
@cmichaelgraham Thanks a mil, will be greatly appreciated.

**Comment by cmichaelgraham** [comment]
@louislewis2 this is a reference to another issue in another repo: https://github.com/aurelia/router/issues/177

**Comment by louislewis2** [comment]
@cmichaelgraham  Last commit implements this feature. I just need to test everything before closing this issue. :)

**Comment by cmichaelgraham** [comment]
You rock !! :)
